// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROG_POE_Part_1.Data;

#nullable disable

namespace PROG_POE_Part_1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251120165754_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PROG_POE_Part_1.Models.Claim", b =>
                {
                    b.Property<int>("Claim_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Claim_ID"));

                    b.Property<DateTime>("Date_Submitted")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Hourly_Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Lecturer_ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_Hours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total_Payment")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Claim_ID");

                    b.HasIndex("Lecturer_ID");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("PROG_POE_Part_1.Models.ClaimReview", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ClaimID")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewerRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ClaimID");

                    b.ToTable("ClaimReviews");
                });

            modelBuilder.Entity("PROG_POE_Part_1.Models.UploadedDocument", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("UploadedDocuments");
                });

            modelBuilder.Entity("PROG_POE_Part_1.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "alice.hr@example.com",
                            HourlyRate = 0m,
                            Name = "Alice",
                            Password = "1234",
                            Role = "HR",
                            Surname = "HR"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "bob.lecturer@example.com",
                            HourlyRate = 200m,
                            Name = "Bob",
                            Password = "1234",
                            Role = "Lecturer",
                            Surname = "Lecturer"
                        },
                        new
                        {
                            UserID = 3,
                            Email = "charlie.coord@example.com",
                            HourlyRate = 0m,
                            Name = "Charlie",
                            Password = "1234",
                            Role = "Coordinator",
                            Surname = "Coordinator"
                        },
                        new
                        {
                            UserID = 4,
                            Email = "diana.manager@example.com",
                            HourlyRate = 0m,
                            Name = "Diana",
                            Password = "1234",
                            Role = "Manager",
                            Surname = "Manager"
                        });
                });

            modelBuilder.Entity("PROG_POE_Part_1.Models.Claim", b =>
                {
                    b.HasOne("PROG_POE_Part_1.Models.User", null)
                        .WithMany()
                        .HasForeignKey("Lecturer_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PROG_POE_Part_1.Models.ClaimReview", b =>
                {
                    b.HasOne("PROG_POE_Part_1.Models.Claim", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ClaimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PROG_POE_Part_1.Models.UploadedDocument", b =>
                {
                    b.HasOne("PROG_POE_Part_1.Models.Claim", null)
                        .WithMany("Documents")
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PROG_POE_Part_1.Models.Claim", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
